"""add default prompts to user

Revision ID: c51b8a5e6bab
Revises: f498a3e04271
Create Date: 2026-03-06 13:07:41.285508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51b8a5e6bab'
down_revision = 'f498a3e04271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_base_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_analysis_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_product_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_product_info')
        batch_op.drop_column('default_analysis_prompt')
        batch_op.drop_column('default_base_prompt')

    # ### end Alembic commands ###
